import json
import os

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Model Training v4 - Sample (Token) Level Training\n",
            "\n",
            "This notebook removes the heavy speaker-level aggregation (`mean` / `std`). Instead, every utterance (token) is treated as an independent sample during training.\n",
            "\n",
            "To prevent data leakage, we still use `StratifiedGroupKFold` split on `speaker_id`. This means if a speaker is in the test set, *all* of their utterances are in the test set, giving a true out-of-sample performance metric while preserving the underlying token distributions (e.g. distinguishing an 'a' from a 'u').",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "import sys\n",
            "from pathlib import Path\n",
            "\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import seaborn as sns\n",
            "import matplotlib.pyplot as plt\n",
            "\n",
            "from sklearn.base import clone\n",
            "from sklearn.compose import ColumnTransformer\n",
            "from sklearn.impute import SimpleImputer\n",
            "from sklearn.pipeline import Pipeline\n",
            "from sklearn.preprocessing import PowerTransformer, OneHotEncoder, LabelEncoder\n",
            "from sklearn.feature_selection import VarianceThreshold, SelectKBest, f_classif, SelectFromModel\n",
            "from sklearn.metrics import accuracy_score, balanced_accuracy_score, f1_score\n",
            "from sklearn.model_selection import StratifiedGroupKFold\n",
            "from sklearn.linear_model import LogisticRegression\n",
            "from sklearn.ensemble import RandomForestClassifier\n",
            "from sklearn.svm import LinearSVC\n",
            "from xgboost import XGBClassifier\n",
            "from lightgbm import LGBMClassifier\n",
            "\n",
            "sys.path.append('..')\n",
            "from src.features import FeatureOptions, load_feature_tables\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "# Reproducibility & Config\n",
            "RANDOM_SEED = 42\n",
            "np.random.seed(RANDOM_SEED)\n",
            "\n",
            "SELECTED_TOKEN = None # Keep all tokens\n",
            "MIN_SAMPLES_PER_CLASS = 50\n",
            "MAX_SAMPLES_PER_CLASS = 300\n",
            "\n",
            "BALANCE_HEALTHY_TO_PATHOLOGICAL = True\n",
            "UPSAMPLE_HEALTHY_TO_PATHOLOGICAL = True\n",
            "\n",
            "N_SPLITS = 5\n",
            "K_CANDIDATES = [30, 50, 100, 150, 'auto']\n",
            "\n",
            "TARGET_SOURCE_COL_PREFERENCE = 'pathology_de'\n",
            "USE_GROUPED_TARGET = True\n",
            "KEEP_UNMAPPED_LABELS = True\n",
            "UNMAPPED_LABEL = 'Other'\n",
            "\n",
            "DISEASE_GROUP_MAP = {\n",
            "    'Morbus Parkinson': 'Neurological',\n",
            "    'Rekurrensparese': 'Neurological',\n",
            "    'Spasmodische Dysphonie': 'Neurological',\n",
            "    'Phonationsknötchen': 'Structural',\n",
            "    'Stimmlippenpolyp': 'Structural',\n",
            "    'Reinke Ödem': 'Structural',\n",
            "    'Laryngitis': 'Structural',\n",
            "    'Hypotone Dysphonie': 'Functional',\n",
            "    'Hyperfunktionelle Dysphonie': 'Functional',\n",
            "    'Psychogene Dysphonie': 'Functional',\n",
            "    'Funktionelle Dysphonie': 'Functional',\n",
            "    'Phonationsknötchen': 'Structural',\n",
            "    'Reinke Ödem': 'Structural',\n",
            "}\n",
            "\n",
            "opts = FeatureOptions(\n",
            "    prefix=Path('..'),\n",
            "    include_splits=True,\n",
            "    random_seed=RANDOM_SEED,\n",
            "    max_samples_per_class=MAX_SAMPLES_PER_CLASS,\n",
            "    balance_healthy_to_pathological=BALANCE_HEALTHY_TO_PATHOLOGICAL,\n",
            "    upsample_healthy_to_pathological=UPSAMPLE_HEALTHY_TO_PATHOLOGICAL,\n",
            "    selected_token=SELECTED_TOKEN,\n",
            "    num_workers=None,\n",
            ")\n",
            "opts",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "# Load Features (Sample Level)\n",
            "tables = load_feature_tables(options=opts, build_if_missing=True, save_if_built=True)\n",
            "\n",
            "core_df = tables['core'].copy()\n",
            "acoustic_df = tables['acoustic'].copy()\n",
            "multifractal_df = tables['multifractal'].copy()\n",
            "opensmile_df = tables.get('opensmile', pd.DataFrame()).copy()\n",
            "splits_df = tables.get('splits', pd.DataFrame()).copy()\n",
            "\n",
            "df = core_df.merge(acoustic_df, on='sample_key', how='left')\n",
            "df = df.merge(multifractal_df, on='sample_key', how='left')\n",
            "if not opensmile_df.empty:\n",
            "    df = df.merge(opensmile_df, on='sample_key', how='left')\n",
            "if not splits_df.empty:\n",
            "    df = df.merge(splits_df, on='sample_key', how='left')\n",
            "\n",
            "if 'feature_status' in df.columns:\n",
            "    df = df[df['feature_status'].isin(['ok', 'partial_failure'])].copy()\n",
            "if 'acoustic_status' in df.columns:\n",
            "    df = df[df['acoustic_status'] == 'ok'].copy()\n",
            "if 'mf_status' in df.columns:\n",
            "    df = df[df['mf_status'] == 'ok'].copy()\n",
            "if 'opensmile_status' in df.columns:\n",
            "    df = df[df['opensmile_status'] == 'ok'].copy()\n",
            "\n",
            "print('Merged sample-level shape:', df.shape)\n",
            "print('Unique speakers:', df['speaker_id'].nunique())",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "# Build Targets\n",
            "raw_target = df[TARGET_SOURCE_COL_PREFERENCE].astype(str).str.strip()\n",
            "if USE_GROUPED_TARGET:\n",
            "    mapped_target = raw_target.map(DISEASE_GROUP_MAP)\n",
            "    mapped_target = mapped_target.fillna(raw_target if KEEP_UNMAPPED_LABELS else UNMAPPED_LABEL)\n",
            "    df['target_label'] = mapped_target.astype(str)\n",
            "else:\n",
            "    df['target_label'] = raw_target\n",
            "\n",
            "target_col = 'target_label'\n",
            "\n",
            "small_classes = df[target_col].value_counts()[df[target_col].value_counts() < MIN_SAMPLES_PER_CLASS].index.tolist()\n",
            "if small_classes:\n",
            "    print(f'Dropping classes with < {MIN_SAMPLES_PER_CLASS} samples: {small_classes}')\n",
            "    df = df[~df[target_col].isin(small_classes)].copy()\n",
            "\n",
            "display(df[target_col].value_counts().to_frame('sample_count'))",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "# Prep Training Matrices\n",
            "meta_cols = {\n",
            "    'sample_key', 'duplicate_class_key', 'recording_id', 'speaker_id', 'wav_path',\n",
            "    'feature_status', 'feature_error', 'acoustic_status', 'acoustic_error',\n",
            "    'mf_status', 'mf_error', 'opensmile_status', 'opensmile_error',\n",
            "    'split', 'split_seed', 'pathology_de', 'pathology_en', target_col, 'is_healthy',\n",
            "    'token' # We could theoretically OHE token, but leaving out to force audio generalizability first\n",
            "}\n",
            "\n",
            "numeric_cols = [c for c in df.columns if c not in meta_cols and pd.api.types.is_numeric_dtype(df[c])]\n",
            "categorical_cols = ['sex'] if 'sex' in df.columns else []\n",
            "\n",
            "X = df[numeric_cols + categorical_cols].copy()\n",
            "# Binary classification: 1=Healthy, 0=Pathological\n",
            "y_bin = df['is_healthy'].astype(int).copy() \n",
            "y_multi = df[target_col].astype(str).copy()\n",
            "groups = df['speaker_id'].astype(str).copy()\n",
            "\n",
            "print('Total tokens/samples:', len(df))\n",
            "print('Features per sample:', len(numeric_cols))",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "# Preprocessing Pipeline\n",
            "numeric_transformer = Pipeline(steps=[\n",
            "    ('imputer', SimpleImputer(strategy='median')),\n",
            "    ('scaler', PowerTransformer(method='yeo-johnson', standardize=True)),\n",
            "    ('variance', VarianceThreshold(threshold=0.0)),\n",
            "])\n",
            "\n",
            "categorical_transformer = Pipeline(steps=[\n",
            "    ('imputer', SimpleImputer(strategy='most_frequent')),\n",
            "    ('onehot', OneHotEncoder(handle_unknown='ignore'))\n",
            "])\n",
            "\n",
            "preprocessor = ColumnTransformer(\n",
            "    transformers=[\n",
            "        ('num', numeric_transformer, numeric_cols),\n",
            "        ('cat', categorical_transformer, categorical_cols),\n",
            "    ],\n",
            "    remainder='drop',\n",
            ")\n",
            "\n",
            "def make_pipe(model, k=50):\n",
            "    if k == 'auto':\n",
            "        selector = SelectFromModel(LinearSVC(penalty='l1', dual=False, C=0.05, class_weight='balanced', max_iter=2000, random_state=RANDOM_SEED))\n",
            "    else:\n",
            "        selector = SelectKBest(f_classif, k=k)\n",
            "        \n",
            "    return Pipeline(steps=[\n",
            "        ('prep', preprocessor),\n",
            "        ('selector', selector),\n",
            "        ('model', model),\n",
            "    ])",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "def evaluate_binary_sample_cv(model, k, X, y, groups, n_splits=5):\n",
            "    cv = StratifiedGroupKFold(n_splits=n_splits, shuffle=True, random_state=RANDOM_SEED)\n",
            "    \n",
            "    fold_rows = []\n",
            "    for fold, (tr, te) in enumerate(cv.split(X, y, groups), start=1):\n",
            "        X_tr, X_te = X.iloc[tr], X.iloc[te]\n",
            "        y_tr, y_te = y.iloc[tr], y.iloc[te]\n",
            "\n",
            "        pipe = make_pipe(clone(model), k=k)\n",
            "        pipe.fit(X_tr, y_tr)\n",
            "        \n",
            "        # Use standard 0.5 threshold for speed - token level doesn't need aggressive shifting yet\n",
            "        p_te = pipe.predict_proba(X_te)[:, 1]\n",
            "        pred_te = (p_te >= 0.5).astype(int)\n",
            "\n",
            "        fold_rows.append({\n",
            "            'fold': fold,\n",
            "            'accuracy': accuracy_score(y_te, pred_te),\n",
            "            'balanced_accuracy': balanced_accuracy_score(y_te, pred_te),\n",
            "            'f1_macro': f1_score(y_te, pred_te, average='macro', zero_division=0),\n",
            "        })\n",
            "        \n",
            "    fold_df = pd.DataFrame(fold_rows)\n",
            "    return fold_df, {\n",
            "        'accuracy_mean': fold_df['accuracy'].mean(),\n",
            "        'balanced_accuracy_mean': fold_df['balanced_accuracy'].mean(),\n",
            "        'f1_macro_mean': fold_df['f1_macro'].mean(),\n",
            "    }",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "# Binary Classification Run\n",
            "binary_models = {\n",
            "    'LogReg': LogisticRegression(max_iter=2000, class_weight='balanced', random_state=RANDOM_SEED),\n",
            "    'RandomForest': RandomForestClassifier(n_estimators=300, max_depth=10, class_weight='balanced_subsample', random_state=RANDOM_SEED, n_jobs=-1),\n",
            "    'LightGBM': LGBMClassifier(n_estimators=300, learning_rate=0.05, class_weight='balanced', random_state=RANDOM_SEED, n_jobs=-1, verbose=-1),\n",
            "}\n",
            "\n",
            "bin_rows = []\n",
            "for k in K_CANDIDATES:\n",
            "    for model_name, model in binary_models.items():\n",
            "        fold_df, summ = evaluate_binary_sample_cv(model, k, X, y_bin, groups, n_splits=N_SPLITS)\n",
            "        bin_rows.append({'model': model_name, 'k': k, **summ})\n",
            "\n",
            "bin_results = pd.DataFrame(bin_rows).sort_values(by=['balanced_accuracy_mean'], ascending=False).reset_index(drop=True)\n",
            "display(bin_results)",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "# Multi-Class Run (Pathological Only)\n",
            "idx_patho = y_bin == 0\n",
            "X_patho, y_patho, g_patho = X[idx_patho], y_multi[idx_patho], groups[idx_patho]\n",
            "\n",
            "multi_models = {\n",
            "    'RandomForest': RandomForestClassifier(n_estimators=300, max_depth=10, class_weight='balanced_subsample', random_state=RANDOM_SEED, n_jobs=-1),\n",
            "    'LightGBM': LGBMClassifier(n_estimators=300, learning_rate=0.05, class_weight='balanced', random_state=RANDOM_SEED, n_jobs=-1, verbose=-1),\n",
            "}\n",
            "\n",
            "cv = StratifiedGroupKFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_SEED)\n",
            "multi_rows = []\n",
            "\n",
            "for k in ['auto', 50, 100]:\n",
            "    for model_name, model in multi_models.items():\n",
            "        fold_metrics = []\n",
            "        for tr, te in cv.split(X_patho, y_patho, g_patho):\n",
            "            X_tr, X_te = X_patho.iloc[tr], X_patho.iloc[te]\n",
            "            y_tr, y_te = y_patho.iloc[tr], y_patho.iloc[te]\n",
            "\n",
            "            le = LabelEncoder()\n",
            "            y_tr_enc = le.fit_transform(y_tr)\n",
            "            y_te_enc = le.transform(y_te)\n",
            "\n",
            "            pipe = make_pipe(clone(model), k=k)\n",
            "            pipe.fit(X_tr, y_tr_enc)\n",
            "            pred_enc = pipe.predict(X_te)\n",
            "\n",
            "            fold_metrics.append({\n",
            "                'accuracy': accuracy_score(y_te_enc, pred_enc),\n",
            "                'balanced_accuracy': balanced_accuracy_score(y_te_enc, pred_enc),\n",
            "                'f1_macro': f1_score(y_te_enc, pred_enc, average='macro', zero_division=0),\n",
            "            })\n",
            "        fold_df = pd.DataFrame(fold_metrics)\n",
            "        multi_rows.append({\n",
            "            'model': model_name, 'k': k,\n",
            "            'accuracy_mean': fold_df['accuracy'].mean(),\n",
            "            'balanced_accuracy_mean': fold_df['balanced_accuracy'].mean(),\n",
            "            'f1_macro_mean': fold_df['f1_macro'].mean(),\n",
            "        })\n",
            "\n",
            "multi_results = pd.DataFrame(multi_rows).sort_values(by=['balanced_accuracy_mean'], ascending=False).reset_index(drop=True)\n",
            "display(multi_results)",
        ],
    },
]

nb = {"cells": cells, "metadata": {}, "nbformat": 4, "nbformat_minor": 5}
with open(
    "g:/Projects/multifractal-speech-analysis/notebooks/model_training_v4_sample_level.ipynb",
    "w",
) as f:
    json.dump(nb, f, indent=2)

print("Created v4 notebook successfully.")
